// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("dll2exe")>]
[<assembly: AssemblyProductAttribute("dll2exe")>]
[<assembly: AssemblyDescriptionAttribute("Convert CLR library into executable (or just run it)")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "dll2exe"
    let [<Literal>] AssemblyProduct = "dll2exe"
    let [<Literal>] AssemblyDescription = "Convert CLR library into executable (or just run it)"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
